#!/bin/sh

IFS=$'\n'
RANDOM_GEN="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)"
TIMESTAMP=$(date +"%Y%m%d%H%M%S")

printinfo(){ 
    echo -e "[\e[96mINFO\e[0m]: \e[1m$*\e[0m" >&2; 
}
printwarn(){ 
    echo -e "[\e[33mWARN\e[0m]: \e[1m$*\e[0m" >&2; 
}
printerr(){ 
    echo -e "[\e[31mERROR\e[0m]: \e[1m$*\e[0m" >&2; 
}

cowner_record_full_system(){
    mkdir -p /tmp/$RANDOM_GEN/ /var/lib/canonical-ownership/full-system/
    find / -not -path /proc -not -path /dev -not -path /sys \
        > /tmp/$RANDOM_GEN/enlist-$TIMESTAMP
    for preproc in `cat /tmp/$RANDOM_GEN/enlist-$TIMESTAMP`; do
        stat -c "%n %a %u %g" $preproc ; done \
        > /var/lib/canonical-ownership/full-system/saved-list-$TIMESTAMP
}

cowner_find_newest_system_list(){
    NEWEST_LIST=$(ls -t /var/lib/canonical-ownership/full-system/saved-list-* | head -1)
}

cowner_restore_full_system(){
    for rstritems in `cat $NEWEST_LIST`; do
        chmod -v $2 $1
        chown -v $3:$4 $1
    done 2> /var/log/saved-list-$TIMESTAMP-resotre-log
}

cowner_record_full_system
