#!/bin/sh

IFS=$'\n'
RANDOM_GEN="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)"
TIMESTAMP=$(date +"%Y%m%d%H%M%S")

printinfo(){ 
    echo -e "[\e[96mINFO\e[0m]: \e[1m$*\e[0m" >&2; 
}
printwarn(){ 
    echo -e "[\e[33mWARN\e[0m]: \e[1m$*\e[0m" >&2; 
}
printerr(){ 
    echo -e "[\e[31mERROR\e[0m]: \e[1m$*\e[0m" >&2; 
}

usage(){
    printf \
"Canonical Ownership:	Return the files to whom it belong to. 
			Fixes system file ownership and modes.

	--record-system		Record current state of ALL system files.
				(WARNING: may take more than 20 minutes)
	--restore-system	Restore system to latest correct state (assumed).
	--help			Print this help message.
	--version		Version of Canonical Ownership.

"
}

cowner_version(){
    echo "Canonical Version VERSION (a little joke from Microsoft)."

cowner_record_full_system(){
    mkdir -p /tmp/$RANDOM_GEN/ /var/lib/canonical-ownership/full-system/
    find / -not -path /proc -not -path /dev -not -path /sys \
        > /tmp/$RANDOM_GEN/enlist-$TIMESTAMP
    for preproc in `cat /tmp/$RANDOM_GEN/enlist-$TIMESTAMP`; do
        stat -c "%n %a %u %g" $preproc ; done \
        > /var/lib/canonical-ownership/full-system/saved-list-$TIMESTAMP
}

cowner_find_newest_system_list(){
    NEWEST_LIST=$(ls -t /var/lib/canonical-ownership/full-system/saved-list-* | head -1)
}

cowner_restore_full_system(){
    for rstritems in `cat $NEWEST_LIST`; do
        chmod -v $2 $1
        chown -v $3:$4 $1
    done 2> /var/log/saved-list-$TIMESTAMP-resotre-log
}

